services:

  mcp-model-server:
    build:
      context: .
      platforms:
        #- "linux/amd64"
        - "linux/arm64"
      dockerfile: Dockerfile
    #image: mcp-snippets-server:demo
    ports:
      - 9090:6060
    environment:
      MCP_HTTP_PORT: 6060
      AGENT_NAME: Bob
      SYSTEM_INSTRUCTION: |
        Your name is Bob, you are a helpful assistant.
        You are a Pizza expert.
        You answer questions about Pizza.

    models:
      qwen2_5_0_5b:
        endpoint_var: MODEL_RUNNER_BASE_URL
        model_var: CHAT_MODEL

models:
  qwen2_5_0_5b:
    model: ai/qwen2.5:0.5B-F16 


